[[headers]]
  for = "/*.js"  # 匹配所有 JS 文件
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"  # 缓存 1 年，且内容不可变

[[headers]]
  for = "/sensorsdata.min.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/helpers.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"

[[headers]]
  for = "/core.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"

[[headers]]
  for = "/lib.core.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"

[[headers]]
  for = "/adapter.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/wrapper.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"

[[headers]]
  for = "/enhance.min.js"
  [headers.values]
    Cache-Control = "max-age=86400, must-revalidate"